CREATE TABLE `t_click_info` (
  `ID` bigint(22) NOT NULL AUTO_INCREMENT COMMENT '点赞记录ID ',
  `USER_ID` bigint(22) DEFAULT NULL COMMENT '用户ID',
  `BUSINESS_ID` bigint(22) DEFAULT NULL COMMENT ' 点赞业务ID',
  `CREATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_collenction_info` (
  `ID` bigint(22) NOT NULL AUTO_INCREMENT COMMENT '收藏记录ID',
  `USER_ID` bigint(22) DEFAULT NULL COMMENT '用户ID',
  `PRODUCT_ID` bigint(22) DEFAULT NULL COMMENT '产品ID',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `MODIFY_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_consult_info` (
  `ID` bigint(22) NOT NULL AUTO_INCREMENT COMMENT '咨询信息ID',
  `USER_ID` bigint(22) DEFAULT NULL COMMENT '用户ID',
  `SYS_USER_ID` bigint(22) DEFAULT NULL COMMENT '系统用户ID',
  `QUESTION` text COMMENT '咨询问题',
  `ANSWER` text COMMENT '咨询回复',
  `CREATE_TIME` datetime DEFAULT NULL,
  `MODIFY_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `t_exchange_record` (
  `ID` bigint(22) NOT NULL AUTO_INCREMENT COMMENT '兑换记录ID',
  `USER_ID` bigint(22) DEFAULT NULL COMMENT '预约用户ID',
  `PRODUCT_ID` bigint(22) DEFAULT NULL COMMENT '产品ID',
  `USE_POINT` int(11) DEFAULT NULL COMMENT '所用积分',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_reservation` (
  `ID` bigint(22) NOT NULL AUTO_INCREMENT COMMENT '预约ID',
  `NAME` varchar(30) DEFAULT NULL COMMENT '预约人姓名',
  `MOBILE` varchar(11) DEFAULT NULL COMMENT '预约人电话',
  `DEAL_FLAG` varchar(1) DEFAULT NULL COMMENT '是否处理',
  `OPEN_ID` varchar(30) DEFAULT NULL COMMENT '微信ID',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `MODIFY_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_sign_record` (
  `ID` bigint(22) NOT NULL AUTO_INCREMENT COMMENT '签到记录ID',
  `USER_ID` bigint(22) DEFAULT NULL COMMENT '用户ID',
  `POINT` int(11) DEFAULT NULL COMMENT '积分',
  `CREATE_TIME` datetime DEFAULT NULL,
  `MODIFY_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_user` (
  `ID` bigint(22) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `HEAD_PHOTO` varchar(50) DEFAULT NULL COMMENT '头像，暂定是字符',
  `NAME` varchar(30) DEFAULT NULL COMMENT '用户名称',
  `SEX` varchar(10) DEFAULT NULL COMMENT '用户性别',
  `MOBILE` varchar(11) DEFAULT NULL COMMENT '用户手机',
  `POINT` int(11) DEFAULT NULL COMMENT '积分',
  `OPEN_ID` varchar(30) DEFAULT NULL COMMENT '微信ID',
  `CREATE_TIME` datetime DEFAULT NULL,
  `MODIFY_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table t_reservation;
drop table reservation;



CREATE TABLE `t_reservation` (
  `ID` int(22) NOT NULL AUTO_INCREMENT COMMENT '预约管理',
  `USER_NAME` varchar(50) DEFAULT NULL,
  `PHONE_NUM` varchar(11) DEFAULT NULL,
  `RESERVATION_DATE_BEGIN` datetime DEFAULT NULL,
  `RESERVATION_DATE_END` datetime DEFAULT NULL,
  `COMMENT` varchar(1000) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `DEAL_FLAG` varchar(1) DEFAULT NULL COMMENT '是否处理',
  `OPEN_ID` varchar(30) DEFAULT NULL COMMENT '微信ID',
  `MODIFY_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

